---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all


  roles:
    - common

- name: configure and deploy the webservers and application code
  hosts: webservers:Type_webservers:tag_Type_webservers


  roles:
    - web

- name: deploy Mariadb and configure the databases
  hosts: dbservers:Type_dbservers:tag_Type_dbservers


  roles:
    - db
