
# all commented variable need to be defined here, or passed via Survey or extra vars in Tower

#aws_access_key: ''
#aws_secret_key: ''
#cloud_name: ''
#vpc_cidr: ''
#region: ''
#user_name: ''
ansible_group: "{{ user_name }}"
security_group_name: "{{ cloud_name }}_SECGRP"
vpc_subnet_name: "{{ cloud_name }}_Subnet"
rt_name: "{{ cloud_name }}_RT_Internet"
igw_name: "{{ cloud_name }}_IGW"
my_email_address: "{{ user_name }}@redhat.com"
#alwaysup: ''
#deleteby: ''
