---
  -  name: Creating Public Static IP for Subnet {{ subnetname }}
     azure_rm_publicipaddress:
       resource_group: "{{ cloud_name }}"
       name: "{{ cloud_name }}{{ '_PublicIP' }}"
       allocation_method: static
       tags:
         created: ansbile
         delete: never
         demo: "{{ customer }}"
         use: SubnetIP
