---
  - name: Adding Subnet to Network {{ cloud_name }}
    azure_rm_subnet:
      resource_group: "{{ cloud_name }}"
      name: "{{ cloud_name }}{{ '_net1' }}"
      address_prefix_cidr: "{{ cidr }}"
      virtual_network_name: "{{ cloud_name }}"
  - include: createpublicipsub.yml
    vars:
      subnetname: "{{ cloud_name }}{{ '_net1' }}"
