---
- name: Create a resource group {{ cloud_name }}
  azure_rm_resourcegroup:
    name: "{{ cloud_name }}"
    location: "{{ region }}"
    tags:
      ansible_group: "{{ ansible_group }}"
      Createdby: Ansible Tower
      Contact: "{{ my_email_address }}"
      DeleteBy: "{{ deleteby }}"
- include: createsubnet.yml
