---
- name: Plex Maintenace
  hosts: all
  gather_facts: False
  tasks:
    - name: Upgrade Plex Media Server Stable release
      ansible.builtin.apt:
        name: plexmediaserver
        state: latest
  #  - name: Check locast2tuner is running and updated container
  #    community.docker.docker_compose:
  #    project_src: /home/locast2tuner/
  #      files: docker-compose.yml
  #      state: present
  #      restarted: yes
  #      pull: yes
  # - name: Check Tautulli is running and updated container
  #   community.docker.docker_compose:
  #      project_src: /home/locast2tuner/
  #      files: docker-tautulli.yml
  #      state: present
  #     restarted: yes
  #     pull: yes
