
---
- name: Setting Interface Description
  hosts: all
  gather_facts: False
  roles:
    - ansible-network.network-engine
  vars:
    ansible_connection: ''
    ansible_network_os: ''
  tasks:
    - name: get show interface
      ios_command:
        commands:
            - show interface
      register: iface_output

    - name: Debug iface_output
      debug:
        var: iface_output
    - name: PARSE THE RAW OUTPUT
      command_parser:
        file: "./PARSER_interface.yml"
        content: "{{ iface_output.stdout[0] }}"
