---
- name: Set Login Banner
  hosts: all
  
  gather_facts: False


  tasks:
    -  name: configure the login banner
       ios_banner:
         banner: login
         text: |
            ______________________ATTENTION_______________________________
            Everybody Loves Ansible it makes Network Jobs easier
            You should not be logging in to this device unless it is an
                                  EMERGENCY
            Please us Ansible automation platfrom and playbooks for changes
