---
- name: Run CLI Command
  hosts: all
  gather_facts: False
  vars:
    ansible_connection: ''
    ansible_network_os: ''
    community: ''
    location: ''
    contact: ''
    host: ''


  tasks:
   - name: Configure SNMP
     ios_config:
       lines:
         - snmp-server community "{{community}}" RO
         - snmp-server location "{{location}}"
         - snmp-server contact "{{contact}}"
         - snmp-server host "{{host}}" version 2c public
       match: line
       replace: block
