---
- name: Configure Vlans
  hosts: ios
  gather_facts: False
  vars:
    ansible_connection: ''
    ansible_network_os: ''
    vlan_name: ''
    vlan_id: ''
    vlan_state: ''



  tasks:
   - name: to devices
     ios_vlan:
       name: "{{vlan_name}}"
       vlan_id: "{{vlan_id}}"
       state: "{{vlan_state}}"
