---
- name: Setting Interface Description
  hosts: all
  gather_facts: False
  vars:
    ansible_connection: ''
    ansible_network_os: ''

  tasks:

  - name: Setting Description on {{int_name}}
    ios_interfaces:
      config:
        - name: "{{int_name}}"
          description: 'Configured by Ansible Tower'
      state: replaced
