---
- name: Run command and print to terminal window
  hosts: all
  gather_facts: false
  vars:
    command: ''
    ansible_connection: ''
    ansible_network_os: ''


  tasks:
    - name: Run {{command}} command!
      cli_command:
        command: "{{command}}"
      register: command_output
