---
# Playbook to test new roles and tags
- name: Create Cloud instance in Azure or AWS
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - role: aws_create_vpc
      tags: ['aws']
    - role: azure_create_vpc
      tags: ['azure']
  vars:
     aws_access_key: ''  #provided by tower
     aws_secret_key: ''  #provided by tower
     AZURE_CLIENT_ID: '' #provided by tower
     AZURE_SECRET: ''    #provided by tower
     AZURE_SUBSCRIPTION_ID: ''  #provided by tower
     AZURE_TENANT: ''    #provided by tower
     ansible_group: "{{ user_name }}"
     security_group_name: "{{ cloud_name }}_SECGRP"
     vpc_subnet_name: "{{ cloud_name }}_Subnet"
     rt_name: "{{ cloud_name }}_RT_Internet"
     igw_name: "{{ cloud_name }}_IGW"
     my_email_address: "{{ user_name }}@redhat.com"
