---
- name: Backup the Arista config with {{ansible_network_os}}
  eos_config:
    backup: yes
    backup_options:
      dir_path: "{{backup_path}}"
      filename: "{{inventory_hostname}}.cfg"
  register: config_output
