---
# This playbook will install mysql and create db user and give permissions.

- name: Install Mariadb package
  yum: 
    name:
      - mariadb-server
      - MySQL-python
      - libselinux-python
      - libsemanage-python
    state: present
- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes
  when: sestatus.rc != 0

- name: Create Mariadb configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mariadb

- name: Start Mysql Service
  service: name=mariadb state=started enabled=yes

- name: Open ports needed
  service:
    name: firewalld
    state: stopped
    enabled: False
  ignore_errors: yes
- name: Create Application Database
  mysql_db: name={{ dbname }} state=present

- name: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
