---
# This playbook contains common plays that will be run on all nodes.
# Gather the start time to use in a later playbook
- name: Record the lamp_time
  ansible.builtin.command:
    cmd: "date '+%H:%M:%S'"
  delegate_to: 127.0.0.1
  register: lamp_time_pre
  run_once: true

# Make the start time available to other playbooks
- name: Capture the lamp_time
  ansible.builtin.set_stats:
    data:
      lamp_time: "{{ lamp_time_pre.stdout }}"
  run_once: true

- name: Install ntp
  yum: name=ntp state=present
  tags: ntp


- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp


- name: Start the ntp service
  service: name=ntpd state=started enabled=yes
  tags: ntp
  

- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false
